# Generated by Django 5.0.6 on 2026-06-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitallog',
            name='bun',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='BUN (mg/dL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vitallog',
            name='creatinine',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Serum Creatinine (mg/dL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vitallog',
            name='gfr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GFR (mL/min)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vitallog',
            name='hba1c',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='HbA1c (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vitallog',
            name='hemoglobin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hemoglobin (g/dL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vitallog',
            name='potassium',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Serum Potassium (mEq/L)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vitallog',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Serum Sodium (mEq/L)', max_digits=5, null=True),
        ),
    ]
